version: "3"
services:
  nginx:
    image: nginx-simple:latest
    container_name: nginx-simple
    restart: always
    ports:
      - 8888:80
    network_mode: "bridge"
    volumes:
      - ./wwwroot/:/var/www/
    build:
      context: .
